#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title: Philipp Hahn
author: Philipp Hahn

# Short bio or description (displayed in the header)
description: Open Source Software Developer

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/965550?s=460&v=4

#
# Flags below are optional
#

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://blog.pmhahn.de

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: pmhahn@pmhahn.de
  facebook: pmhahn75
  flickr:
  github: pmhahn
  instagram:
  linkedin:
  pinterest:
  rss: true
  twitter:
  stackoverflow: users/907658/pmhahn  # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube:  # channel/<your_long_string> or user/<user-name>
  googleplus:  # 110059045397851960899  # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Time zone
timezone: Europe/Berlin

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

show_drafts: false
future: false
unpublished: false
lsi: true

# The release of Jekyll Now that you're using
version: v3.9.5

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
  auto_ids: true

# Pagination
pagination:
  enabled: true
  debug: false
  per_page: 10

# Use the following plug-ins
plugins:
  - jekyll-sitemap  # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed  # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate-v2
  - classifier-reborn

# Exclude these files from your production _site
exclude:
  - sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - CNAME

# Install: sudo apt install jekyll ruby-jekyll-paginate-v2 ruby-jekyll-sitemap ruby-jekyll-feed ruby-classifier-reborn
# Build: jekyll b
# Serve: jekyll s
